name: Merge to main
on:
  workflow_dispatch:
  workflow_call:

# Cancel if a newer run is started
concurrency:
  group: ${{ github.workflow }}-main
  cancel-in-progress: true

jobs:
  publish-documentation:
    if: github.repository == 'nf-neuro/modules'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: dispatch documentation deployment
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.DOCUMENTATION_PUBLISHING }}
          repository: nf-neuro/nf-neuro.github.io
          event-type: publish-documentation

  publish-extension-package:
    if: github.repository == 'nf-neuro/modules'
    permissions:
      contents: read
    uses: ./.github/workflows/publish_extension.yml
    with:
      name: "extension-package"
    secrets: inherit
