name: Merge to main
on:
  workflow_dispatch:
  workflow_call:

# Cancel if a newer run is started
concurrency:
  group: ${{ github.workflow }}-main
  cancel-in-progress: true

jobs:
  publish-documentation:
    if: github.repository == 'nf-neuro/modules'
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: nf-neuro/website/.github/workflows/deploy.yml@main
    secrets: inherit

  publish-extension-package:
    if: github.repository == 'nf-neuro/modules'
    permissions:
      contents: read
    uses: ./.github/workflows/publish_extension.yml
    with:
      name: "extension-package"
    secrets: inherit
